<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Db2\MasterMiniplant;

class MasterMiniplantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            // =====================================================
            // PA - Produk Kulit dan Alas Kaki
            // =====================================================
            [
                'id' => 1,
                'kode' => 'PA',
                'jenis_jasa' => 'proses',
                'nama' => 'Pembuatan Barang Kulit/ Alas Kaki » Sepatu Moccasin',
                'satuan' => 'per pc',
                'biaya' => 205000,
            ],
            [
                'id' => 2,
                'kode' => 'PA',
                'jenis_jasa' => 'proses',
                'nama' => 'Pembuatan Barang Kulit/ Alas Kaki » Sepatu non Moccasin',
                'satuan' => 'per pc',
                'biaya' => 143000,
            ],
            [
                'id' => 3,
                'kode' => 'PA',
                'jenis_jasa' => 'proses',
                'nama' => 'Pembuatan Barang Kulit/ Alas Kaki » Sepatu bot',
                'satuan' => 'per pc',
                'biaya' => 164000,
            ],
            [
                'id' => 4,
                'kode' => 'PA',
                'jenis_jasa' => 'proses',
                'nama' => 'Pembuatan Barang Kulit/ Alas Kaki » Sandal/selop',
                'satuan' => 'per pc',
                'biaya' => 119000,
            ],
            [
                'id' => 5,
                'kode' => 'PA',
                'jenis_jasa' => 'proses',
                'nama' => 'Pembuatan Barang Kulit/ Alas Kaki » Garmen Kulit',
                'satuan' => 'per pc',
                'biaya' => 222000,
            ],
            [
                'id' => 6,
                'kode' => 'PA',
                'jenis_jasa' => 'proses',
                'nama' => 'Pembuatan Barang Kulit/ Alas Kaki » Tas selempang',
                'satuan' => 'per pc',
                'biaya' => 153000,
            ],
            [
                'id' => 7,
                'kode' => 'PA',
                'jenis_jasa' => 'proses',
                'nama' => 'Pembuatan Barang Kulit/ Alas Kaki » Tas punggung/ransel',
                'satuan' => 'per pc',
                'biaya' => 161000,
            ],
            [
                'id' => 8,
                'kode' => 'PA',
                'jenis_jasa' => 'proses',
                'nama' => 'Pembuatan Barang Kulit/ Alas Kaki » Tas tangan',
                'satuan' => 'per pc',
                'biaya' => 101000,
            ],
            [
                'id' => 9,
                'kode' => 'PA',
                'jenis_jasa' => 'proses',
                'nama' => 'Pembuatan Barang Kulit/ Alas Kaki » Dompet/map',
                'satuan' => 'per pc',
                'biaya' => 58000,
            ],
            [
                'id' => 10,
                'kode' => 'PA',
                'jenis_jasa' => 'proses',
                'nama' => 'Pembuatan Barang Kulit/ Alas Kaki » Tempat kartu/lanyard',
                'satuan' => 'per pc',
                'biaya' => 44000,
            ],
            [
                'id' => 11,
                'kode' => 'PA',
                'jenis_jasa' => 'proses',
                'nama' => 'Pembuatan Barang Kulit/ Alas Kaki » Ikat pinggang',
                'satuan' => 'per pc',
                'biaya' => 51000,
            ],
            [
                'id' => 12,
                'kode' => 'PA',
                'jenis_jasa' => 'proses',
                'nama' => 'Pembuatan Barang Kulit/ Alas Kaki » Asesoris pakaian',
                'satuan' => 'per pc',
                'biaya' => 53000,
            ],

            // =====================================================
            // RPK - Riset Penyamakan Kulit
            // =====================================================
            [
                'id' => 13,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Sapi » Kulit pikel sampai dengan wetblue',
                'satuan' => 'sqft',
                'biaya' => 4500,
            ],
            [
                'id' => 14,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Sapi » Kulit pikel sampai dengan kras natural',
                'satuan' => 'sqft',
                'biaya' => 4500,
            ],
            [
                'id' => 15,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Sapi » Kulit pikel sampai dengan kras warna',
                'satuan' => 'sqft',
                'biaya' => 12000,
            ],
            [
                'id' => 16,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Sapi » Kulit wetblue sampai dengan kras warna',
                'satuan' => 'sqft',
                'biaya' => 6000,
            ],
            [
                'id' => 17,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Domba/Kambing » Kulit mentah sampai dengan pikel',
                'satuan' => 'sqft',
                'biaya' => 4000,
            ],
            [
                'id' => 18,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Domba/Kambing » Kulit mentah sampai dengan tersamak',
                'satuan' => 'sqft',
                'biaya' => 6000,
            ],
            [
                'id' => 19,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Domba/Kambing » Kulit mentah sampai dengan kras',
                'satuan' => 'sqft',
                'biaya' => 10000,
            ],
            [
                'id' => 20,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Domba/Kambing » Kulit pikel sampai dengan tersamak',
                'satuan' => 'sqft',
                'biaya' => 6000,
            ],
            [
                'id' => 21,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Domba/Kambing » Kulit pikel sampai dengan kras',
                'satuan' => 'sqft',
                'biaya' => 7000,
            ],
            [
                'id' => 22,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Domba/Kambing » Kulit wetblue sampai dengan kras',
                'satuan' => 'sqft',
                'biaya' => 5000,
            ],
            [
                'id' => 23,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Domba/Kambing » Kulit mentah sampai dengan kras bulu',
                'satuan' => 'sqft',
                'biaya' => 20000,
            ],
            [
                'id' => 24,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Kelinci » Kulit samak bulu',
                'satuan' => 'lembar',
                'biaya' => 24000,
            ],
            [
                'id' => 25,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Kelinci » Kulit glace',
                'satuan' => 'lembar',
                'biaya' => 24000,
            ],
            [
                'id' => 26,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Ular » Kulit kras natural',
                'satuan' => 'm panjang & 10 cm lebar',
                'biaya' => 46000,
            ],
            [
                'id' => 27,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Ular » Kulit kras warna',
                'satuan' => 'm panjang & 10 cm lebar',
                'biaya' => 46000,
            ],
            [
                'id' => 28,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Biawak » Kulit kras natural',
                'satuan' => 'm panjang & 10 cm lebar',
                'biaya' => 45000,
            ],
            [
                'id' => 29,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Biawak » Kulit kras warna',
                'satuan' => 'm panjang & 10 cm lebar',
                'biaya' => 49000,
            ],
            [
                'id' => 30,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Buaya » Kulit kras natural',
                'satuan' => 'inchi',
                'biaya' => 14000,
            ],
            [
                'id' => 31,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Buaya » Kulit kras warna',
                'satuan' => 'inchi',
                'biaya' => 20000,
            ],
            [
                'id' => 32,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Ikan Pari » Kulit kras natural',
                'satuan' => 'inchi',
                'biaya' => 14000,
            ],
            [
                'id' => 33,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Ikan Pari » Kulit kras warna',
                'satuan' => 'inchi',
                'biaya' => 19000,
            ],
            [
                'id' => 34,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Ikan Kakap » Kulit kras natural',
                'satuan' => 'm panjang & 10 cm lebar',
                'biaya' => 49000,
            ],
            [
                'id' => 35,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Ikan Kakap » Kulit kras warna',
                'satuan' => 'm panjang & 10 cm lebar',
                'biaya' => 55000,
            ],
            [
                'id' => 36,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Ikan Nila » Kulit kras natural',
                'satuan' => 'lembar',
                'biaya' => 12000,
            ],
            [
                'id' => 37,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Ikan Nila » Kulit kras warna',
                'satuan' => 'lembar',
                'biaya' => 17000,
            ],
            [
                'id' => 38,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Kaki Ayam » Kulit kras natural',
                'satuan' => '10 lembar',
                'biaya' => 49000,
            ],
            [
                'id' => 39,
                'kode' => 'RPK',
                'jenis_jasa' => 'proses',
                'nama' => 'Penyamakan Kulit Kaki Ayam » Kulit kras warna',
                'satuan' => '10 lembar',
                'biaya' => 50000,
            ],
            [
                'id' => 40,
                'kode' => 'RPK',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Drum Penyamakan » Drum penyamakan (trial)',
                'satuan' => 'jam',
                'biaya' => 21000,
            ],
            [
                'id' => 41,
                'kode' => 'RPK',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Drum Penyamakan » Drum penyamakan (kecil)',
                'satuan' => 'jam',
                'biaya' => 35000,
            ],
            [
                'id' => 42,
                'kode' => 'RPK',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Drum Penyamakan » Drum penyamakan (sedang)',
                'satuan' => 'jam',
                'biaya' => 45000,
            ],
            [
                'id' => 43,
                'kode' => 'RPK',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Drum Penyamakan » Drum penyamakan (besar)',
                'satuan' => 'jam',
                'biaya' => 51000,
            ],

            // =====================================================
            // F - Finishing Kulit
            // =====================================================
            [
                'id' => 44,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Staking Vibration » Hide',
                'satuan' => '50 perlakuan',
                'biaya' => 40000,
            ],
            [
                'id' => 45,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Staking Vibration » Skin',
                'satuan' => '50 lembar',
                'biaya' => 40000,
            ],
            [
                'id' => 46,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Staking Wheel',
                'satuan' => '50 lembar',
                'biaya' => 40000,
            ],
            [
                'id' => 47,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Embossing (Mostardini) » Motif polos hide',
                'satuan' => '10 side',
                'biaya' => 25000,
            ],
            [
                'id' => 48,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Embossing (Mostardini) » Motif polos skin',
                'satuan' => '10 lembar',
                'biaya' => 17000,
            ],
            [
                'id' => 49,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Embossing (Mostardini) » Motif polos kulit eksotis',
                'satuan' => '20 lembar',
                'biaya' => 19000,
            ],
            [
                'id' => 50,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Embossing (Mostardini) » Motif pori hide',
                'satuan' => '25 side',
                'biaya' => 63000,
            ],
            [
                'id' => 51,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Embossing (Mostardini) » Motif pori skin',
                'satuan' => '50 lembar',
                'biaya' => 91000,
            ],
            [
                'id' => 52,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Ironing (Satilux) » Skin (maksimum 3 detik)',
                'satuan' => '10 lembar',
                'biaya' => 17000,
            ],
            [
                'id' => 53,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Ironing (Satilux) » Skin (penambahan waktu per 3 detik)',
                'satuan' => '50 lembar',
                'biaya' => 25000,
            ],
            [
                'id' => 54,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Toggling » Hide',
                'satuan' => '10 side',
                'biaya' => 20000,
            ],
            [
                'id' => 55,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Toggling » Skin',
                'satuan' => '10 lembar',
                'biaya' => 14000,
            ],
            [
                'id' => 56,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Toggling » Kulit buaya',
                'satuan' => '10 lembar',
                'biaya' => 19000,
            ],
            [
                'id' => 57,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Toggling » Kulit biawak',
                'satuan' => '10 lembar',
                'biaya' => 14000,
            ],
            [
                'id' => 58,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Toggling » Kulit ular',
                'satuan' => '10 lembar',
                'biaya' => 19000,
            ],
            [
                'id' => 59,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Brushing » Hide',
                'satuan' => '50 side',
                'biaya' => 51000,
            ],
            [
                'id' => 60,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Brushing » Skin',
                'satuan' => '50 lembar',
                'biaya' => 38000,
            ],
            [
                'id' => 61,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Measuring » Hide',
                'satuan' => '50 side',
                'biaya' => 51000,
            ],
            [
                'id' => 62,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Measuring » Skin',
                'satuan' => '50 lembar',
                'biaya' => 38000,
            ],
            [
                'id' => 63,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Milling » Hide',
                'satuan' => 'jam',
                'biaya' => 30000,
            ],
            [
                'id' => 64,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Milling » Skin',
                'satuan' => 'jam',
                'biaya' => 25000,
            ],
            [
                'id' => 65,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Glazing » Hide',
                'satuan' => '20 sqft',
                'biaya' => 51000,
            ],
            [
                'id' => 66,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Glazing » Skin',
                'satuan' => '20 sqft',
                'biaya' => 38000,
            ],
            [
                'id' => 67,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Glazing » Kulit reptil',
                'satuan' => '20 lembar',
                'biaya' => 12000,
            ],
            [
                'id' => 68,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Spraying » Kompresor',
                'satuan' => 'jam',
                'biaya' => 250000,
            ],
            [
                'id' => 69,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Spraying » Spray gun',
                'satuan' => 'jam',
                'biaya' => 38000,
            ],
            [
                'id' => 70,
                'kode' => 'F',
                'jenis_jasa' => 'mesin',
                'nama' => 'Jasa Mesin Fleshing » Skin',
                'satuan' => '10 lembar',
                'biaya' => 17000,
            ],

            // =====================================================
            // MKP - Miniplant Karet dan Plastik
            // =====================================================
            [
                'id' => 71,
                'kode' => 'MKP',
                'jenis_jasa' => 'proses',
                'nama' => 'Pembuatan Kompon (Karet alam)',
                'satuan' => 'per kg',
                'biaya' => 114000,
            ],
            [
                'id' => 72,
                'kode' => 'MKP',
                'jenis_jasa' => 'proses',
                'nama' => 'Pembuatan Kompon (Karet sintetis)',
                'satuan' => 'per kg',
                'biaya' => 130000,
            ],
            [
                'id' => 73,
                'kode' => 'MKP',
                'jenis_jasa' => 'proses',
                'nama' => 'Pembuatan slab karet',
                'satuan' => 'per lembar',
                'biaya' => 80000,
            ],
            [
                'id' => 74,
                'kode' => 'MKP',
                'jenis_jasa' => 'proses',
                'nama' => 'Pembuatan slab plastik',
                'satuan' => 'per lembar',
                'biaya' => 65000,
            ],
            [
                'id' => 75,
                'kode' => 'MKP',
                'jenis_jasa' => 'proses',
                'nama' => 'Kematangan kompon / Rheometer',
                'satuan' => 'per contoh',
                'biaya' => 137000,
            ],
            [
                'id' => 76,
                'kode' => 'MKP',
                'jenis_jasa' => 'proses',
                'nama' => 'Melt Flow Indexer',
                'satuan' => 'per contoh',
                'biaya' => 160000,
            ],
            [
                'id' => 77,
                'kode' => 'MKP',
                'jenis_jasa' => 'proses',
                'nama' => 'Rebound Ressilience',
                'satuan' => 'per contoh',
                'biaya' => 150000,
            ],
        ];

        foreach ($data as $item) {
            MasterMiniplant::updateOrCreate(
                ['id' => $item['id']],
                [
                    'kode' => $item['kode'],
                    'jenis_jasa' => $item['jenis_jasa'],
                    'nama' => $item['nama'],
                    'satuan' => $item['satuan'],
                    'biaya' => $item['biaya'],
                    'is_active' => true,
                ]
            );
        }
    }
}
