services:
    private_polimer_2_wsl:
        container_name: private-polimer-2-wsl
        build:
            context: .
            dockerfile: ./docker/dockerfile/app.Dockerfile
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www
        networks:
            - bbkkp_network
        ports:
            - "4903:80"
        depends_on:
            - mysql_wsl

    mysql_wsl:
        image: mysql:8.0
        container_name: private-mysql-wsl
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: private_polimer
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: bbkkp
            MYSQL_PASSWORD: bbkkp_password
        ports:
            - "3311:3306"
        volumes:
            - private_mysql_data_wsl:/var/lib/mysql
        networks:
            - bbkkp_network

    minio_wsl:
        image: minio/minio:latest
        container_name: private-minio-wsl
        restart: unless-stopped
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: miniopassword123
        ports:
            - "9004:9000"
            - "9005:9001"
        volumes:
            - private_minio_data_wsl:/data
        command: server /data --console-address ":9001"
        networks:
            - bbkkp_network

networks:
    bbkkp_network:
        external: true

volumes:
    private_mysql_data_wsl:
    private_minio_data_wsl:
